# Generated by Django 3.1.1 on 2020-09-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailentry',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='emailentry',
            name='name',
        ),
    ]
