# Generated by Django 3.1.1 on 2020-09-03 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20200903_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailentry',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
